server:
  port: 9998

user-service:
 service-url: http://localhost:7766
spring:
  cloud:
    gateway:
      routes:
       - id: path_route
         uri: ${user-service.service-url}/user/{id}
         predicates:
          - Path=/user/{id}

logging:
 level:
  org.springframework: debug
  com.zss.gateway: debug