
server:
  port: 9992


spring:
  application:
    name: eureka-client


logging:
 level:
  org.springframework: debug



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone:  http://slave1:1111/eureka,http://slave2:1112/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html


