
server:
  port: 9992


spring:
  application:
    name: eureka-client








logging:
 level:
  org.springframework: debug



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone:  http://localhost:9991/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


