server:
  port: 2587
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.1.66:8848
logging:
  level:
   com.alibaba: debug
   com.zss.nacos: debug
   org.springframework: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
