server:
  port: 9526
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://zss:123@localhost:8888/eureka/

logging:
 level:
  org.springframework: debug
  com.zss.turbine: debug

turbine:
  app-config: hystrix-service #指定需要收集信息的服务名称
  cluster-name-expression: new String('default') #指定服务所属集群
  combine-host-port: true #以主机名和端口号来区分服务

