server:
  port: 9525
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://zss:123@localhost:8888/eureka/

logging:
 level:
  org.springframework: debug
  com.zss.feign: debug
  com.zss.feign.service.UserService: debug
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
  httpclient:
    enabled: false
  okhttp:
    enabled: true

#feign自己的配置
#feign:
#  hystrix:
#    enabled: true #在Feign中开启Hystrix
#  compression:
#    request:
#      enabled: false #是否对请求进行GZIP压缩
#      mime-types: text/xml,application/xml,application/json #指定压缩的请求数据类型
#      min-request-size: 2048 #超过该大小的请求会被压缩
#    response:
#      enabled: false #是否对响应进行GZIP压缩
#logging:
#  level: #修改日志级别
#    com.zss.feign.service.UserService: debug

#ribbon 和 hyxtrix可以直接使用配置