server:
  port: 9524
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://zss:123@localhost:8888/eureka/

logging:
 level:
  org.springframework: debug
  com.zss.zuul: debug
zuul:
  routes:
   user-service:
    path: /userService/**
   feign-service:
    path: /feignService/**
  ignored-services: user-service,feign-service
  prefix: /zss
  sensitive-headers: Cookie,Set-Cookie,Authorization
  add-host-header: true
  PreLogFilter:
   pre:
    disable: true
management:
  endpoints:
    web:
      exposure:
        include: 'routes'

hystrix:
  command: #用于控制HystrixCommand的行为
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理

ribbon: #全局配置
  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
